services:
  postgres:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  rabbit:
    image: rabbitmq:3
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASSWORD
  worker:
    links: [ rabbit ]
    depends_on: [ rabbit ]
    build:
      dockerfile: ./docker/Dockerfile
    entrypoint: ["/celery_entrypoint.sh"]
  django:
    links: [ postgres ]
    depends_on: [ postgres, redis, rabbit ]
    build:
      dockerfile: ./docker/Dockerfile
      args:
        - WEB_APP_PORT=$WEB_APP_PORT
    volumes:
      - ./example:/example
    ports:
      - $WEB_APP_PORT:$WEB_APP_PORT
    entrypoint: [ "/django_entrypoint.sh" ]

networks:
  default: